/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.event.ActionListener;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author muchamad fuad
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    private CardLayout cardLayout;
    
    public MainMenu() {
        initComponents();
        cardLayout = new CardLayout();
        jPanel1.setLayout(cardLayout);
    }
    
    
    public CardLayout getCardLayout() {
        return cardLayout;
    }
    
    public JPanel getjPanel1() {
        return jPanel1;
    }
    
    public JMenuItem getMnDaftarPaket() {
        return mnDaftarPaket;
    }

    public JMenuItem getMnDaftarPelanggan() {
        return mnDaftarPelanggan;
    }

    public JMenuItem getMnDaftarTempatWisata() {
        return mnDaftarTempatWisata;
    }

    public JMenuItem getMnDeletePaket() {
        return mnDeletePaket;
    }

    public JMenuItem getMnDeletePelanggan() {
        return mnDeletePelanggan;
    }

    public JMenuItem getMnDeleteTempatWisata() {
        return mnDeleteTempatWisata;
    }

    public JMenuItem getMnEditPaket() {
        return mnEditPaket;
    }

    public JMenuItem getMnEditPelanggan() {
        return mnEditPelanggan;
    }

    public JMenuItem getMnInsertJadwalPerjalanan() {
        return mnInsertJadwalPerjalanan;
    }

    public JMenuItem getMnInsertPelanggan() {
        return mnInsertPelanggan;
    }

    public JMenuItem getMnInsertTempatWisata() {
        return mnInsertTempatWisata;
    }

    public JMenuItem getMnNewPaket() {
        return mnNewPaket;
    }

    public JMenuItem getMnViewJadwalPerjalanan() {
        return mnViewJadwalPerjalanan;
    }
    
    public void addListener(ActionListener e) {
        mnInsertPelanggan.addActionListener(e);
        mnDeletePelanggan.addActionListener(e);
        mnEditPelanggan.addActionListener(e);
        mnDaftarPelanggan.addActionListener(e);
        mnInsertTempatWisata.addActionListener(e);
        mnDeleteTempatWisata.addActionListener(e);
        mnDaftarTempatWisata.addActionListener(e);
        mnNewPaket.addActionListener(e);
        mnEditPaket.addActionListener(e);
        mnDeletePaket.addActionListener(e);
        mnDaftarPaket.addActionListener(e);
        mnInsertJadwalPerjalanan.addActionListener(e);
        mnViewJadwalPerjalanan.addActionListener(e);  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPelanggan = new javax.swing.JMenu();
        mnInsertPelanggan = new javax.swing.JMenuItem();
        mnEditPelanggan = new javax.swing.JMenuItem();
        mnDeletePelanggan = new javax.swing.JMenuItem();
        mnDaftarPelanggan = new javax.swing.JMenuItem();
        menuTempatWisata = new javax.swing.JMenu();
        mnInsertTempatWisata = new javax.swing.JMenuItem();
        mnDeleteTempatWisata = new javax.swing.JMenuItem();
        mnDaftarTempatWisata = new javax.swing.JMenuItem();
        menuPaketWisata = new javax.swing.JMenu();
        mnNewPaket = new javax.swing.JMenuItem();
        mnEditPaket = new javax.swing.JMenuItem();
        mnDeletePaket = new javax.swing.JMenuItem();
        mnDaftarPaket = new javax.swing.JMenuItem();
        menuJadwalPerjalanan = new javax.swing.JMenu();
        mnInsertJadwalPerjalanan = new javax.swing.JMenuItem();
        mnViewJadwalPerjalanan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 250));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        jMenuBar1.setMaximumSize(new java.awt.Dimension(500, 32769));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(400, 40));

        menuPelanggan.setText("Pelanggan   ");
        menuPelanggan.setToolTipText("");

        mnInsertPelanggan.setText("Insert Pelanggan");
        menuPelanggan.add(mnInsertPelanggan);

        mnEditPelanggan.setText("Edit Pelanggan");
        menuPelanggan.add(mnEditPelanggan);

        mnDeletePelanggan.setText("Delete Pelanggan");
        menuPelanggan.add(mnDeletePelanggan);

        mnDaftarPelanggan.setText("Daftar Pelanggan");
        menuPelanggan.add(mnDaftarPelanggan);

        jMenuBar1.add(menuPelanggan);

        menuTempatWisata.setText("Tempat Wisata    ");

        mnInsertTempatWisata.setText("Insert Tempat Wisata");
        menuTempatWisata.add(mnInsertTempatWisata);

        mnDeleteTempatWisata.setText("Delete Tempat Wisata");
        menuTempatWisata.add(mnDeleteTempatWisata);

        mnDaftarTempatWisata.setText("Daftar Tempat Wisata");
        menuTempatWisata.add(mnDaftarTempatWisata);

        jMenuBar1.add(menuTempatWisata);

        menuPaketWisata.setText("Paket Wisata   ");

        mnNewPaket.setText("New Paket");
        menuPaketWisata.add(mnNewPaket);

        mnEditPaket.setText("Edit Paket");
        menuPaketWisata.add(mnEditPaket);

        mnDeletePaket.setText("Delete Paket");
        menuPaketWisata.add(mnDeletePaket);

        mnDaftarPaket.setText("Daftar Paket");
        menuPaketWisata.add(mnDaftarPaket);

        jMenuBar1.add(menuPaketWisata);

        menuJadwalPerjalanan.setText("Jadwal Perjalanan");

        mnInsertJadwalPerjalanan.setText("Insert");
        menuJadwalPerjalanan.add(mnInsertJadwalPerjalanan);

        mnViewJadwalPerjalanan.setText("View");
        menuJadwalPerjalanan.add(mnViewJadwalPerjalanan);

        jMenuBar1.add(menuJadwalPerjalanan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuJadwalPerjalanan;
    private javax.swing.JMenu menuPaketWisata;
    private javax.swing.JMenu menuPelanggan;
    private javax.swing.JMenu menuTempatWisata;
    private javax.swing.JMenuItem mnDaftarPaket;
    private javax.swing.JMenuItem mnDaftarPelanggan;
    private javax.swing.JMenuItem mnDaftarTempatWisata;
    private javax.swing.JMenuItem mnDeletePaket;
    private javax.swing.JMenuItem mnDeletePelanggan;
    private javax.swing.JMenuItem mnDeleteTempatWisata;
    private javax.swing.JMenuItem mnEditPaket;
    private javax.swing.JMenuItem mnEditPelanggan;
    private javax.swing.JMenuItem mnInsertJadwalPerjalanan;
    private javax.swing.JMenuItem mnInsertPelanggan;
    private javax.swing.JMenuItem mnInsertTempatWisata;
    private javax.swing.JMenuItem mnNewPaket;
    private javax.swing.JMenuItem mnViewJadwalPerjalanan;
    // End of variables declaration//GEN-END:variables
}
